import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/routes/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/layouts/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "electric-blue": "#0062ff",
        "midnight-navy": "#0a1128",
        "soft-white": "#f8f9fa",
        // Radix UI gray scale
        gray1: "var(--gray1)",
        gray2: "var(--gray2)",
        gray3: "var(--gray3)",
        gray4: "var(--gray4)",
        gray5: "var(--gray5)",
        gray6: "var(--gray6)",
        gray7: "var(--gray7)",
        gray8: "var(--gray8)",
        gray9: "var(--gray9)",
        gray10: "var(--gray10)",
        gray11: "var(--gray11)",
        gray12: "var(--gray12)",
        // Radix UI blue scale
        blue1: "var(--blue1)",
        blue2: "var(--blue2)",
        blue3: "var(--blue3)",
        blue4: "var(--blue4)",
        blue5: "var(--blue5)",
        blue6: "var(--blue6)",
        blue7: "var(--blue7)",
        blue8: "var(--blue8)",
        blue9: "var(--blue9)",
        blue10: "var(--blue10)",
        blue11: "var(--blue11)",
        blue12: "var(--blue12)",
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "SF Pro Display",
          "SF Pro Text",
          "Segoe UI",
          "Roboto",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        "eb-garamond": ["EB Garamond", "serif"],
        pretendard: ["Pretendard", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
        mondwest: ["var(--font-mondwest)", "sans-serif"],
        neuebit: ["var(--font-neuebit)", "sans-serif"],
        sfpro: [
          "-apple-system",
          "BlinkMacSystemFont",
          "SF Pro Display",
          "SF Pro Text",
          "Segoe UI",
          "Roboto",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        "sf-pro": [
          "-apple-system",
          "BlinkMacSystemFont",
          "SF Pro Display",
          "SF Pro Text",
          "Segoe UI",
          "Roboto",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
      },
    },
  },
  plugins: [],
};

export default config;
