"""
Agentic AI Labs — pSEO Research Engine
run_research.py — Master Runner

USAGE:
  python run_research.py [slug]

  Where [slug] matches a key in config/industry_map.py

EXAMPLES:
  python run_research.py dental-practices
  python run_research.py recruiting-agencies
  python run_research.py ghl-agencies
  python run_research.py vapi-alternative

OUTPUT:
  A research brief .txt file saved to the relevant playbook's _research_briefs/ folder.
  Example: ../01_PERSONAS/_research_briefs/dental-practices.txt

WHAT IT DOES:
  1. Looks up the slug in config/industry_map.py
  2. Fires all 5 research nodes (BLS, Reddit, Trends, RSS, Jobs)
  3. Combines all output into a single formatted .txt brief
  4. Saves the brief to the correct playbook folder
  5. Prints a summary of what was collected and where to find the file
"""

import sys
import os
import time
from datetime import datetime

# ── Resolve paths relative to this script ────────────────────────────────────
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)   # Programmatic SEO/

# Add RESEARCH_ENGINE to sys.path so imports work
sys.path.insert(0, SCRIPT_DIR)

# ── Playbook → folder mapping ─────────────────────────────────────────────────
PLAYBOOK_FOLDERS = {
    "01_PERSONAS":     os.path.join(PROJECT_ROOT, "01_PERSONAS",     "_research_briefs"),
    "02_INTEGRATIONS": os.path.join(PROJECT_ROOT, "02_INTEGRATIONS", "_research_briefs"),
    "03_COMPARISONS":  os.path.join(PROJECT_ROOT, "03_COMPARISONS",  "_research_briefs"),
    "04_GLOSSARY":     os.path.join(PROJECT_ROOT, "04_GLOSSARY",     "_research_briefs"),
    "05_LOCATIONS":    os.path.join(PROJECT_ROOT, "05_LOCATIONS",    "_research_briefs"),
    "06_DIRECTORY":    os.path.join(PROJECT_ROOT, "06_DIRECTORY",    "_research_briefs"),
}


def print_banner(slug: str):
    print("")
    print("╔══════════════════════════════════════════════════════════════════════╗")
    print("║   AGENTIC AI LABS — PSEO RESEARCH ENGINE                           ║")
    print(f"║   Slug: {slug:<60} ║")
    print(f"║   Time: {datetime.now().strftime('%Y-%m-%d %H:%M'): <60} ║")
    print("╚══════════════════════════════════════════════════════════════════════╝")
    print("")


def run_node(name: str, module, config: dict) -> str:
    """Runs a single research node and returns its output string."""
    print(f"  ▶  Running {name}...", end="", flush=True)
    try:
        result = module.run(config)
        print(" ✓")
        return result
    except Exception as e:
        print(f" ✗ ERROR: {e}")
        return f"{name}\n{'─' * 60}\n  [ERROR] Node failed: {str(e)}\n"


def build_brief(slug: str, config: dict, node_outputs: list) -> str:
    """Assembles all node outputs into the final brief document."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    header = f"""
╔══════════════════════════════════════════════════════════════════════════════╗
║        RESEARCH BRIEF                                                       ║
║        {config.get('page_title', slug):<72} ║
╠══════════════════════════════════════════════════════════════════════════════╣
║  Slug:        {slug:<63} ║
║  Playbook:    {config.get('playbook', 'unknown'):<63} ║
║  Generated:   {now:<63} ║
║  AI Role:     {config.get('role', 'N/A'):<63} ║
║  Industry:    {config.get('industry', 'N/A'):<63} ║
║  Replaces:    {config.get('replaced_role', 'N/A'):<63} ║
╚══════════════════════════════════════════════════════════════════════════════╝

  HOW TO USE THIS BRIEF
  ─────────────────────────────────────────────────────────────────────────────
  1. Read the UNIQUE DATA POINTS summary at the bottom of this file.
  2. Open the corresponding page copy .txt file.
  3. Replace placeholder values with the real numbers from this brief.
  4. Cite sources inline (citation templates provided per node).
  5. Keep this brief — re-run research monthly to stay fresh.

  This brief was generated automatically by RESEARCH_ENGINE/run_research.py
  Do NOT edit this file manually — re-run the script to refresh data.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

    separator = "\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
    body = separator.join(node_outputs)

    footer = f"""

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  UNIQUE DATA POINTS SUMMARY
  (Pull these directly into the page copy — they're what differentiates the page)
  ─────────────────────────────────────────────────────────────────────────────

  FROM NODE 01 (BLS):
    • Real median/mean salary for the role being replaced
    • National employment count for context ("there are X of these jobs")

  FROM NODE 02 (Reddit):
    • Verbatim practitioner quotes describing the pain
    • Upvote counts as social validation signal

  FROM NODE 03 (Google Trends):
    • Growth % for the target keyword over 12 months
    • Rising related queries → use as additional page sections/subheadings

  FROM NODE 04 (RSS):
    • Most recent industry headline with date
    • Any statistics extracted from article summaries

  FROM NODE 05 (Jobs):
    • Open job count for the role being replaced (live)
    • Salary ranges from live job postings

  ─────────────────────────────────────────────────────────────────────────────
  Generated by:   RESEARCH_ENGINE/run_research.py
  Config source:  RESEARCH_ENGINE/config/industry_map.py
  Next refresh:   Run this script again in 30 days
  ─────────────────────────────────────────────────────────────────────────────
"""
    return header + body + footer


def main():
    if len(sys.argv) < 2:
        print("\nUsage: python run_research.py [slug]")
        print("\nAvailable slugs (from config/industry_map.py):")
        from config.industry_map import INDUSTRY_MAP
        for key in sorted(INDUSTRY_MAP.keys()):
            print(f"  {key}")
        sys.exit(1)

    slug = sys.argv[1].strip()
    print_banner(slug)

    # ── Load config ──────────────────────────────────────────────────────────
    try:
        from config.industry_map import get_config
        config = get_config(slug)
    except KeyError as e:
        print(str(e))
        sys.exit(1)

    print(f"  Config loaded: {config['page_title']}")
    print(f"  Playbook:      {config['playbook']}")
    print("")

    # ── Import nodes ─────────────────────────────────────────────────────────
    from nodes import node_01_bls_labor
    from nodes import node_02_reddit_pain
    from nodes import node_03_google_trends
    from nodes import node_04_rss_news
    from nodes import node_05_job_market

    # ── Run each node ─────────────────────────────────────────────────────────
    print("Running research nodes:")
    outputs = []
    outputs.append(run_node("Node 01 — BLS Labor Data",     node_01_bls_labor,     config))
    time.sleep(1)
    outputs.append(run_node("Node 02 — Reddit Pain",        node_02_reddit_pain,   config))
    time.sleep(3)
    outputs.append(run_node("Node 03 — Google Trends",      node_03_google_trends, config))
    time.sleep(5)  # Longer delay after Trends to avoid rate limit
    outputs.append(run_node("Node 04 — RSS News Feed",      node_04_rss_news,      config))
    time.sleep(1)
    outputs.append(run_node("Node 05 — Job Market",         node_05_job_market,    config))

    print("")

    # ── Build and save the brief ─────────────────────────────────────────────
    brief_content = build_brief(slug, config, outputs)

    playbook_key = config.get("playbook", "01_PERSONAS")
    output_dir   = PLAYBOOK_FOLDERS.get(playbook_key, PLAYBOOK_FOLDERS["01_PERSONAS"])
    os.makedirs(output_dir, exist_ok=True)

    output_file = os.path.join(output_dir, f"{slug}.txt")
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(brief_content)

    # ── Done ─────────────────────────────────────────────────────────────────
    print("╔══════════════════════════════════════════════════════════════════════╗")
    print("║   RESEARCH COMPLETE                                                 ║")
    print(f"║   Brief saved to:                                                   ║")
    rel_path = os.path.relpath(output_file, PROJECT_ROOT)
    print(f"║   {rel_path:<68} ║")
    print("╚══════════════════════════════════════════════════════════════════════╝")
    print("")
    print("  Next steps:")
    print(f"  1. Open: {rel_path}")
    print("  2. Read the UNIQUE DATA POINTS section at the bottom")
    print(f"  3. Update the page copy file for slug: {slug}")
    print("")


if __name__ == "__main__":
    main()
