#!/usr/bin/env python3
"""
WhatsApp Community Chat Analyzer — Voice AI Builders
Parses the exported chat, extracts pain points, questions, keyword clusters,
and generates a structured SEO opportunity report.

Usage:
    python3 analyze_community.py
    python3 analyze_community.py --input voiceai_community_whatsapp.txt
"""

import re
import os
import argparse
from datetime import datetime
from collections import Counter, defaultdict

# ── Config ────────────────────────────────────────────────────────────────────

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
DEFAULT_INPUT  = os.path.join(SCRIPT_DIR, "voiceai_community_whatsapp.txt")
DEFAULT_OUTPUT = os.path.join(SCRIPT_DIR, "community_analysis.md")

# Topic clusters — keyword groups that define a theme
TOPIC_CLUSTERS = {
    "Latency Optimization":      ["latency", "lag", "delay", "slow", "ms", "millisecond", "ttft",
                                   "time to first", "response time", "p50", "p90", "p95", "p99",
                                   "fast", "faster", "speed", "optimize latency"],
    "STT / Speech-to-Text":      ["stt", "asr", "speech-to-text", "transcription", "transcript",
                                   "deepgram", "speechmatics", "whisper", "google stt", "azure stt",
                                   "word error", "wer", "accuracy", "endpointing"],
    "TTS / Voice Quality":       ["tts", "text-to-speech", "elevenlabs", "eleven labs", "cartesia",
                                   "playht", "voice quality", "voice clone", "natural voice",
                                   "synthetic", "robotic"],
    "LLM Choice & Prompting":    ["llm", "gpt", "claude", "gemini", "groq", "llama", "haiku",
                                   "prompt", "system prompt", "context", "token", "hallucinate",
                                   "hallucination", "fine-tun", "fine tune"],
    "Platform: Vapi":            ["vapi"],
    "Platform: LiveKit":         ["livekit", "livekit"],
    "Platform: Pipecat":         ["pipecat"],
    "Platform: Bland / Retell":  ["bland", "retell"],
    "Telephony Infrastructure":  ["twilio", "telnyx", "plivo", "exotel", "sip", "pstn", "voip",
                                   "trunk", "telephony", "number", "phone number", "cps",
                                   "concurrent", "codec", "g711", "g722", "8khz", "16khz"],
    "Call Pickup & Spam":        ["pickup rate", "pick up", "spam", "truecaller", "marked spam",
                                   "blocked", "number rotation", "airtel", "jio", "series",
                                   "cold call", "outbound"],
    "Answering Machine Detection": ["amd", "answering machine", "voicemail", "voicemail detection",
                                    "machine detection", "human detection", "beep"],
    "Conversation Design":       ["barge", "interrupt", "turn detection", "vad", "silence",
                                   "conversation flow", "script", "objection", "sales flow",
                                   "end of turn", "end-of-turn"],
    "Noise Cancellation":        ["noise", "krisp", "noise cancel", "noisy", "background",
                                   "nc ", "audio quality"],
    "Scaling & Infrastructure":  ["scale", "concurrent", "k8s", "kubernetes", "docker",
                                   "self-host", "cloud", "aws", "gcp", "azure", "server",
                                   "livekit cost", "infrastructure cost"],
    "HIPAA / Compliance":        ["hipaa", "compliance", "gdpr", "data retention", "pii",
                                   "redact", "security", "regulation", "trai", "tcpa"],
    "Sales & First Customer":    ["first customer", "paying customer", "cold outreach", "sales",
                                   "get client", "close", "demo", "convert"],
    "QA / Monitoring":           ["qa", "quality assurance", "monitoring", "observability",
                                   "test", "cekura", "benchmark", "eval", "evaluation"],
    "Multilingual / Non-English": ["hindi", "hinglish", "italian", "nepali", "turkish",
                                    "multilingual", "non-english", "language", "code-mix"],
    "CRM Integration":           ["crm", "salesforce", "hubspot", "gohighlevel", "ghl",
                                   "integration", "webhook", "api call", "function call"],
}

# Noise to filter out (system messages)
SYSTEM_PATTERNS = [
    r"joined using a group link",
    r"was added",
    r"added .+ to",
    r"changed the settings",
    r"pinned a message",
    r"removed .+",
    r"created this group",
    r"Messages and calls are end-to-end encrypted",
    r"Welcome to the group",
    r"This message was deleted",
    r"changed the group",
    r"Only messages that mention",
    r"Messages are generated by AI",
]


# ── Parser ────────────────────────────────────────────────────────────────────

MSG_RE = re.compile(
    r'^\[(\d{2}/\d{2}/\d{2,4}),\s+(\d{1,2}:\d{2}:\d{2}\s*[AP]M)\]\s+~?\s*([^:]+):\s*(.+)$',
    re.DOTALL
)

def is_system(text):
    for pat in SYSTEM_PATTERNS:
        if re.search(pat, text, re.IGNORECASE):
            return True
    return False

def parse_chat(filepath):
    messages = []
    with open(filepath, encoding="utf-8") as f:
        lines = f.readlines()

    current = None
    for line in lines:
        line = line.rstrip("\n")
        m = MSG_RE.match(line)
        if m:
            if current:
                messages.append(current)
            date_str, time_str, sender, text = m.groups()
            sender = sender.strip()
            text   = text.strip()
            if not is_system(text) and len(text) > 3:
                current = {"date": date_str, "time": time_str,
                           "sender": sender, "text": text, "lines": [text]}
            else:
                current = None
        else:
            # Continuation line
            if current:
                current["text"] += "\n" + line
                current["lines"].append(line)

    if current:
        messages.append(current)

    return messages


# ── Analysis ──────────────────────────────────────────────────────────────────

def classify_topics(text):
    text_lower = text.lower()
    matched = []
    for topic, keywords in TOPIC_CLUSTERS.items():
        if any(kw in text_lower for kw in keywords):
            matched.append(topic)
    return matched

def extract_questions(messages):
    return [m for m in messages if "?" in m["text"] and len(m["text"]) > 20]

def extract_pain_points(messages):
    """Messages expressing frustration, confusion, problems."""
    pain_signals = [
        "issue", "problem", "not working", "struggling", "challenge",
        "confused", "how do", "how can", "how to", "can someone",
        "anyone know", "help", "stuck", "fails", "failing", "fail",
        "doesn't work", "not sure", "slow", "bad", "poor", "wrong",
        "fix", "improve", "reduce", "optimize", "can't", "cannot",
        "still not", "any solution", "any suggestion", "recommendation",
        "facing", "we're facing", "i'm facing"
    ]
    results = []
    for m in messages:
        tl = m["text"].lower()
        if any(sig in tl for sig in pain_signals) and len(m["text"]) > 30:
            results.append(m)
    return results

def topic_frequency(messages):
    counts = Counter()
    for m in messages:
        for topic in classify_topics(m["text"]):
            counts[topic] += 1
    return counts

def top_questions_by_topic(questions):
    by_topic = defaultdict(list)
    for q in questions:
        for topic in classify_topics(q["text"]):
            by_topic[topic].append(q["text"][:200].strip())
    return by_topic


# ── Report builder ────────────────────────────────────────────────────────────

def build_report(messages, questions, pain_points, topic_counts, q_by_topic):
    lines = []
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    total_msgs = len(messages)
    unique_senders = len({m["sender"] for m in messages})
    date_range = f"{messages[0]['date']} – {messages[-1]['date']}" if messages else "N/A"

    lines.append("# Voice AI Community Chat Analysis")
    lines.append(f"**Generated:** {now}  |  **Source:** voiceai_community_whatsapp.txt")
    lines.append(f"**Messages analyzed:** {total_msgs}  |  **Unique participants:** {unique_senders}  |  **Period:** {date_range}\n")
    lines.append("---\n")

    # ── Topic heatmap
    lines.append("## Topic Heatmap — What the Community Is Talking About\n")
    lines.append("| Topic | Message count | Signal strength |")
    lines.append("|---|---|---|")
    for topic, count in topic_counts.most_common():
        bar = "█" * min(count // 2, 20) + "░" * max(0, 20 - count // 2)
        lines.append(f"| **{topic}** | {count} | `{bar}` |")
    lines.append("")
    lines.append("---\n")

    # ── Top questions by topic
    lines.append("## Real Questions Being Asked (Verbatim)\n")
    lines.append("These are direct quotes from the community — the exact searches they will do next.\n")
    for topic, count in topic_counts.most_common(10):
        qs = q_by_topic.get(topic, [])
        if not qs:
            continue
        lines.append(f"### {topic}\n")
        for q in qs[:4]:
            clean = q.replace("\n", " ").strip()
            lines.append(f'> "{clean}"\n')
        lines.append("")

    lines.append("---\n")

    # ── Raw pain point messages
    lines.append("## High-Signal Pain Points\n")
    lines.append("Messages expressing frustration, confusion, or unsolved problems.\n")
    shown = set()
    count = 0
    for m in pain_points:
        preview = m["text"][:250].replace("\n", " ").strip()
        key = preview[:60]
        if key in shown or len(preview) < 40:
            continue
        shown.add(key)
        lines.append(f"**[{m['sender']}]** {preview}{'...' if len(m['text']) > 250 else ''}\n")
        count += 1
        if count >= 25:
            break

    lines.append("---\n")

    # ── SEO opportunities
    lines.append("## SEO Content Opportunities\n")
    lines.append("Derived from actual community pain points — these are searches that exist but have zero or thin content.\n")

    opportunities = [
        {
            "cluster": "Latency Optimization",
            "title": "How to reduce voice AI latency below 600ms — stack by stack breakdown",
            "angle": "Community obsessed with this. Real benchmarks shared (Groq=fastest, GPT-4o-mini sweet spot, Cartesia fastest TTS). Nobody has written the definitive guide with actual numbers.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "How-to / technical",
            "urgency": "🔴 High",
        },
        {
            "cluster": "Platform: Vapi",
            "title": "Why builders move from Vapi to LiveKit/Pipecat — and when to make the switch",
            "angle": "Direct quotes: 'Vapi good for demos/POC but if you need control and customization it's bad'. Common migration pattern. No content exists on this transition.",
            "internal_link": "/vapi-alternative",
            "search_intent": "Comparison / decision",
            "urgency": "🔴 High",
        },
        {
            "cluster": "Call Pickup & Spam",
            "title": "Why your AI outbound calls get marked as spam — and how to fix it",
            "angle": "Most active non-technical discussion. Number series strategy (9 vs 80), Truecaller verification backfiring, Airtel/Jio 15-day cooling period. Pure pain, no good content.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "Problem / fix",
            "urgency": "🔴 High",
        },
        {
            "cluster": "Answering Machine Detection",
            "title": "AMD for AI voice agents — how to detect voicemail under 2 seconds",
            "angle": "Very specific technical problem discussed at length. TCPA compliance angle, 90%+ accuracy requirement, CPU vs GPU approaches.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "Technical how-to",
            "urgency": "🟠 Medium-High",
        },
        {
            "cluster": "LLM Choice & Prompting",
            "title": "Multi-stage sales flow with voice AI — how to stop the LLM from skipping steps",
            "angle": "Insurance company asked 8 detailed questions on this. No content exists. Dynamic injection vs monolith prompt, multi-agent orchestrator for sales stages.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "Technical problem / architecture",
            "urgency": "🟠 Medium-High",
        },
        {
            "cluster": "QA / Monitoring",
            "title": "Voice AI QA and observability — what to monitor before you go to production",
            "angle": "Cekura raised $2.4M solving this. Community asking 'something like Datadog for voice agents'. No agency is writing about this. Targets retainer buyers.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "Awareness / problem recognition",
            "urgency": "🟠 Medium-High",
        },
        {
            "cluster": "Telephony Infrastructure",
            "title": "Twilio vs Telnyx vs Plivo for voice AI — honest comparison in 2026",
            "angle": "Constantly referenced and debated. Telnyx = 16kHz true audio, Twilio = most battle-tested, Plivo = India-specific strength. Real builders want this comparison.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "Comparison",
            "urgency": "🟠 Medium-High",
        },
        {
            "cluster": "Scaling & Infrastructure",
            "title": "LiveKit vs Pipecat — which framework to use and when (from builders in production)",
            "angle": "Poll: LiveKit 11 votes, Pipecat 6 votes, Others 9. Heavy discussion. LiveKit = scaling + WebRTC native. Pipecat = faster to build. No neutral comparison exists.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "Comparison / decision",
            "urgency": "🟡 Medium",
        },
        {
            "cluster": "HIPAA / Compliance",
            "title": "HIPAA compliance for voice AI in healthcare — what you actually need to do",
            "angle": "Discussed multiple times. $5-10M lawsuit risk. Data deletion under 30 mins, no storage, redaction. Healthcare buyers search this before buying anything.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "Compliance research",
            "urgency": "🟡 Medium",
        },
        {
            "cluster": "Multilingual / Non-English",
            "title": "Voice AI latency for non-English languages — what actually works",
            "angle": "Hinglish, Italian, Nepali discussed. Real finding: English models have lower latency. Gemini best for multilingual. 8kHz India telephony vs 16kHz US. India-specific market gap.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "Technical / market-specific",
            "urgency": "🟡 Medium",
        },
        {
            "cluster": "Sales & First Customer",
            "title": "How to get your first paying client for an AI voice agent business",
            "angle": "Asked multiple times in the chat. Real answers: cold LinkedIn outreach, industry connections, lead with outcomes. No fluff — people want the real answer.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "Business / growth",
            "urgency": "🟡 Medium",
        },
        {
            "cluster": "Conversation Design",
            "title": "Voice agent keeps talking over the user — debugging barge-in and VAD issues",
            "angle": "Specific technical complaint shared verbatim. LLM not waiting, TTS speaking continuously. Context engineering, VAD config, flushing audio queues. Zero content on this.",
            "internal_link": "/ai-voice-agent",
            "search_intent": "Debugging / fix",
            "urgency": "🟡 Medium",
        },
    ]

    for i, opp in enumerate(opportunities, 1):
        lines.append(f"### {i}. {opp['title']}")
        lines.append(f"**Cluster:** {opp['cluster']}  |  **Intent:** {opp['search_intent']}  |  **Priority:** {opp['urgency']}")
        lines.append(f"**Why:** {opp['angle']}")
        lines.append(f"**Internal link:** `{opp['internal_link']}`\n")

    lines.append("---\n")

    # ── Keyword raw frequency
    all_words = " ".join(m["text"].lower() for m in messages)
    keywords_of_interest = [
        "latency", "vapi", "livekit", "pipecat", "deepgram", "elevenlabs",
        "cartesia", "twilio", "telnyx", "plivo", "exotel", "groq", "gpt",
        "gemini", "spam", "pickup", "voicemail", "hipaa", "compliance",
        "stt", "tts", "llm", "websocket", "sip", "noise", "barge",
        "turn detection", "vad", "concurrent", "scale", "india", "hindi",
        "hinglish", "retell", "bland", "n8n", "gohighlevel",
    ]
    lines.append("## Raw Keyword Frequency\n")
    lines.append("| Keyword | Mentions |")
    lines.append("|---|---|")
    kw_counts = [(kw, all_words.count(kw)) for kw in keywords_of_interest]
    kw_counts.sort(key=lambda x: -x[1])
    for kw, cnt in kw_counts:
        if cnt > 0:
            lines.append(f"| `{kw}` | {cnt} |")

    lines.append("\n---\n")
    lines.append(f"*Analysis generated by Agentic AI Labs | {now}*")

    return "\n".join(lines)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Analyze WhatsApp community chat for SEO insights")
    parser.add_argument("--input",  default=DEFAULT_INPUT,  help="Path to WhatsApp .txt export")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Output markdown report path")
    args = parser.parse_args()

    print(f"\nParsing: {args.input}")
    messages = parse_chat(args.input)
    print(f"  {len(messages)} messages parsed")

    questions    = extract_questions(messages)
    pain_points  = extract_pain_points(messages)
    topic_counts = topic_frequency(messages)
    q_by_topic   = top_questions_by_topic(questions)

    print(f"  {len(questions)} questions found")
    print(f"  {len(pain_points)} pain point signals found")
    print(f"  {len(topic_counts)} topic clusters identified")

    report = build_report(messages, questions, pain_points, topic_counts, q_by_topic)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"\n  Report saved: {args.output}")
    print("\n  Top 5 topics:")
    for topic, count in topic_counts.most_common(5):
        print(f"    {count:3d}  {topic}")
    print()


if __name__ == "__main__":
    main()
